aliases:
    aptup: sudo bash -c 'apt-get update && apt-get -y upgrade && apt-get -y dist-upgrade'
    fleeks: cd ~/.local/share/fleek
    ga: git add
    gb: git for-each-ref --sort=committerdate refs/heads/ --format='%(HEAD) %(color:yellow)%(refname:short)%(color:reset) - %(color:red)%(objectname:short)%(color:reset) - %(contents:subject) - %(authorname) (%(color:green)%(committerdate:relative)%(color:reset))'
    gbr: git branch
    gco: git checkout
    gd: git diff
    gs: git status
    gvl: git log | vim -c 'set keywordprg=git\ show' -R -
    lsblk: lsblk -o name,fstype,size,label,uuid
    vcon: 'nvim -p $(git status | grep ''both modified'' | cut -d: -f2)'
bling: default
blocklist: []
byo_git: false
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:
    - overmind
    - lsd
    - asdf-vm
    - pass
    - stow
    - alacritty
paths:
    - $HOME/bin
    - $HOME/.local/bin
    - $HOME/scripts
programs:
    - dircolors
shell: bash
systems:
    - arch: x86_64
      hostname: xps15
      os: linux
      username: benjamin
    - arch: x86_64
      hostname: xps13
      os: linux
      username: benjamin
    - arch: x86_64
      hostname: terra
      os: linux
      username: benjamin
track: nixos-unstable
unfree: true
users:
    - email: ben@madeofpaper.co.uk
      name: Benjamin Martin
      ssh_private_key_file: ~/.ssh/bugthing
      ssh_public_key_file: ~/.ssh/bugthing.pub
      username: benjamin
