name: Fleek Configuration
min_version: 0.8.4
bling: high
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
overlays: {}
unfree: true
packages:
    - overmind
    - lsd
    - asdf-vm
    - pass
    - stow
paths:
    - $HOME/bin
    - $HOME/.local/bin
    - $HOME/scripts
programs:
    - dircolors
shell: bash
aliases:
    fleeks: cd ~/.local/share/fleek
    gs: git status
    ga: git add
    gbr: git branch
    gd: git diff
    gco: git checkout
    gb: git for-each-ref --sort=committerdate refs/heads/ --format='%(HEAD) %(color:yellow)%(refname:short)%(color:reset) - %(color:red)%(objectname:short)%(color:reset) - %(contents:subject) - %(authorname) (%(color:green)%(committerdate:relative)%(color:reset))'
    vcon: "nvim -p $(git status | grep 'both modified' | cut -d: -f2)"
    gvl: git log | vim -c 'set keywordprg=git\ show' -R -
    aptup: sudo bash -c 'apt-get update && apt-get -y upgrade && apt-get -y dist-upgrade'
    lsblk: lsblk -o name,fstype,size,label,uuid
systems:
    - arch: x86_64
      hostname: xps15
      os: linux
      username: benjamin
    - arch: x86_64
      hostname: xps13
      os: linux
      username: benjamin
    - arch: x86_64
      hostname: terra
      os: linux
      username: benjamin
users:
    - email: ben@madeofpaper.co.uk
      name: Benjamin Martin
      ssh_private_key_file: ~/.ssh/bugthing
      ssh_public_key_file: ~/.ssh/bugthing.pub
      username: benjamin
