aliases:
    fleeks: cd ~/.local/share/fleek
bling: default
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:
    - helix
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
shell: bash
systems:
    - arch: x86_64
      hostname: xps15
      os: linux
      username: benjamin
unfree: true
users:
    - email: benjamin247365@hotmail.com
      name: Benjamin Martin
      ssh_private_key_file: ~/.ssh/bugthing
      ssh_public_key_file: ~/.ssh/bugthing.pub
      username: benjamin
